# Generated by Django 2.2.1 on 2019-05-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazonSearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=16)),
                ('title_text', models.CharField(max_length=128)),
                ('publisher', models.CharField(max_length=128)),
                ('marketingservices', models.CharField(max_length=1)),
                ('batch', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
