# Generated by Django 2.2.1 on 2019-05-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazonSearch', '0004_auto_20190511_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='batch',
            field=models.CharField(max_length=8),
        ),
    ]
