# Generated by Django 2.2.1 on 2019-05-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazonSearch', '0006_auto_20190511_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='asin',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='search',
            name='author',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='search',
            name='date',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='search',
            name='image_link',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='search',
            name='publication_date',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='search',
            name='publisher',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='search',
            name='title_text',
            field=models.CharField(max_length=128),
        ),
    ]
